model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  low_resource: True
  max_txt_len: 300
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  llama_model: /mnt/data4/home/ziyuan/MiniGPT4-Finetuning/vicuna-7b
  lora_r: 64
  lora_alpha: 16


datasets:
  flickr30k_grounded_detail:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  flickr30k:
    eval_file_path: /mnt/data4/home/ziyuan/MiniGPT4-Finetuning/flickr30k/flickr30k_grounded_detail.json
    img_path: /mnt/data4/home/ziyuan/MiniGPT4-Finetuning/flickr30k/flickr30k-images
    max_new_tokens: 60
    batch_size: 16

run:
  task: image_text_pretrain
  name: minigpt4_flickr_eval